env:
  global:
    - CC_TEST_REPORTER_ID=afa5222229deb448b89860668c7b0c19e5d758986b494d755d7a82fe82d2f778
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
